### ISSUE TITLE
What do the .backCircles do? These should be squashed into 1 CSS chunk/class

### ISSUE THREAD

**Issue by addiment** [MaxO-P/Nexus-Demo-Page#2]
```
/* TODO: What do the .backCircles do? These should be squashed into 1 CSS chunk/class */
```

https://github.com/Windzyboy/Nexus-Demo-Page/blob/becd38f4c4d4efbad4f34cda0ed370c34f00cfc0/layout.css#L119

**Comment by MaxO-P** [comment]
they were something i was gonna use but decided against but i was too lazy to remove them 💀 ima do that rn

**Comment by MaxO-P** [comment]
done
